# Generated by Django 3.0.5 on 2020-11-08 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mid_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_name', models.CharField(db_index=True, max_length=200)),
                ('mid_meta_description', models.TextField(blank=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'mid_category',
                'verbose_name_plural': 'mid_categories',
                'ordering': ['mid_name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='mid_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.Mid_Category'),
        ),
    ]
