# Generated by Django 3.0.5 on 2020-11-15 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201108_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mid_category',
        ),
        migrations.DeleteModel(
            name='Mid_Category',
        ),
    ]
